### ISSUE TITLE
Problemer med parsing af ereolen URL'er

### ISSUE THREAD

**Issue by mikkelam** [jo1gi/grawlix#2]
Hej jo1gi, fedt projekt. Det lykkedes mig at låne en bog med ereoelen :-) med lidt edits.

Jeg prøvede at låne denne bog https://ereolen.dk/ting/object/870970-basis%3A46960386/read og jeg tror at din regex ikke er helt glad for den url, jeg replacede blot `book_id` manuelt

udover der tror jeg at linje 31 i __main__.py skal være
`library = options.library`

**Comment by jo1gi** [comment]
> Jeg prøvede at låne denne bog https://ereolen.dk/ting/object/870970-basis%3A46960386/read og jeg tror at din regex ikke er helt glad for den url, jeg replacede blot `book_id` manuelt

Tror det er fikset nu. Ikke helt sikker. Sig til, hvis det ikke virker.

> udover der tror jeg at linje 31 i **main**.py skal være
> `library = options.library`

Det har du ret i. Har fikset det nu. Tak for hjælpen.
